services:
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - ./frontend/.env

  backend:
    # user: "${UID}:${GID}"
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:3000"
    environment:
      NODE_ENV: development
      npm_config_cache: /usr/src/app/.npm-cache
      USER_ID: ${UID}
      GROUP_ID: ${GID}
    env_file:
      - ./backend/.env

  db:
    image: postgres
    environment:
      POSTGRES_DB: stringfinder
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  db_data:
  pgadmin:
