services:
  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "80:5000"
    environment:
      NODE_ENV: production
