version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  db:
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
